### ISSUE TITLE
Use AppConfig class instead of implicit models.py

### ISSUE THREAD

**Issue by mjtamlyn** [markfinger/python-react#45]
As of django 1.6 models.py files are not needed and you can use an [AppConfig.ready()](https://docs.djangoproject.com/en/1.8/ref/applications/#django.apps.AppConfig.ready) to do explicit setup.

**Comment by markfinger** [comment]
I'm not too familiar with the AppConfig stuff - is there a standard for automatic discovery?

In this project, models.py is only really a hook so that `react.conf.settings` can be configured declaratively from django's settings files. It's a bit of a hack, which used to be necessary due to circular imports - not sure if it's still necessary though.

More than happy to accept to a PR

**Comment by mjtamlyn** [comment]
See https://github.com/django/django/blob/master/django/contrib/gis/__init__.py as an example of the auto discovery - put a dotted path to the app config as `default_app_config` at the module level.

The app config's are there specifically for this use case so it doesn't need to be a hack.
