### ISSUE TITLE
Render Server in watch mode

### ISSUE THREAD

**Issue by anantzoid** [markfinger/python-react#65]
Hi,
Currently, one needs to restart the render_server.js (taken from the examples) everytime any change is made in a component. You have mentioned that resetting the server is required in developement mode, but do you think there's any way if the node server could watch these changes. I tried to find a solution, but still struggling. Constantly restarting the node server during development becomes quite tedious.
Thanks.

**Comment by markfinger** [comment]
Yeah, I generally turn rendering off in development as it's mostly a end-user optimisation that's only relevant in production. It's certainly still worth testing for in dev, but in same sense as testing minified code before a deployment.

There's a setting that you can use to deactivate it: https://github.com/markfinger/python-react#settings

With regards to your question: it's definitely possible, but its a problem that tends to be quite complicated once you start considering the many ways in which people build and/or import code.

If you're using something like webpack to bundle your code into a node-compatible file, you can use something like `fs.watch` or `chokidar` to watch the file and then restart the server.

If you're simply importing the raw files - using something like babel's register-hook for `require` - then it becomes more difficult as you'd probably need to preprocess the files and try to build a dependency graph. It's certainly not impossible, but it'd probably take some wiring to get it working.

If all your code lived in a particular directory tree you might be able to do a recursive watch and then restart the server when anything changes.

Note that you'll probably need to run the server in a parent process so that it can be respawned when it restarts.

Good luck with the investigation.

**Comment by anantzoid** [comment]
Thanks for the quick response. I have a few question regarding what you said though:
1. Setting ```RENDER``` to False stops rendering anything on the page. How can I proceed with development in that case?
2. I tried to bundle everything using webpack and use the webpack --watch too. But then how do I specify the path to the component in ```render_component```. The path has to be a filepath where only that component resides, right?

Anyways, I found [forever](https://github.com/foreverjs/forever) and now using it to watch my components directory for changes and restart the render_server.js

**Comment by markfinger** [comment]
Sorry, I assumed that you had client-side code that took over once the page rendered. If you're only pre-rendering, then `RENDER` is useless.

If you're using webpack, you'd probably need to rig webpack's config to export the specific component from the bundle.

Yeah, forever and [nodemon](https://github.com/remy/nodemon) are a good solution for the problem.

**Comment by mic159** [comment]
Webpack has a concept of entry points, which lets you build multiple bundles, and also lets you have multiple configs at once.
The idea is that you create one config and entry point for the client side, and a different config for the server side.

_webpack.config.js:_
```js
module.exports = [{
    // Server side config
    entry: {
        ComponentOne: ['./src/ComponentOne.jsx'],
        ComponentTwo: ['./src/ComponentTwo.jsx'],
    },
    output: {
        libraryTarget: 'commonjs2',
        filename: '[name].server.js',
        ... etc ...
    },
    ... etc ...
},
{
    // Client side config
    entry: {
      main: ['./src/main.jsx'],
    },
    ... etc ...
}
```

The server side entry point should just be the react component itself, whereas the client side one will probably be a bootstrap function.

Then you give `render_component` the path to the built file `ComponentOne.server.js`.

**Comment by anantzoid** [comment]
Thanks. This helped a lot.
