### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by benjolabs** [markfinger/python-react#82]
I am testing a simple Hello World jsx example to verify my setup works and running into this error:
`'Message: {}\n\nStack trace: {}'.format(err['message'], err['stack'])
ReactRenderingError: Message: document is not defined`

My test jsx looks like this:
```
import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
    <h1>Hello World</h1>,
    document.getElementById('root')
);
```

I can't tell what react-render expects or how it handles this situation

**Comment by markfinger** [comment]
The problem is the `document` reference. `react-render` runs the code in a node process, which doesn't have a `document` reference.

The be more expansive, your test script contains both the components and the bootstrap code (eg: the call to `ReactDOM.render` and `document.getElementById`). The code passed to `react-render` should be only the component that needs to be referenced, in this case it would be `<h1>Hello World</h1>`
