### ISSUE TITLE
callback functions in props?

### ISSUE THREAD

**Issue by mklan** [markfinger/python-react#84]
Hello, is it somehow possible to pass a callback function as prop, which is triggered for example when a onClick event is firing?

**Comment by markfinger** [comment]
**Assuming you want to dynamically generate code**

You could pass a reference to a function:

```
# python
{
    onClickMethod: ['./some-file', 'someMethod']
}
```

```
// JS
let onClickMethod = require(props.onClickMethod[0])[props.onClickMethod[1]);
```

This will trip up bundlers (webpack, etc) though, as the `require` call can't be statically analysed. It also seems like a generally bad idea from an architectural perspective 😄 

I suppose you could pass a function as a string and eval it.

I'd recommend just passing a flag down and having your JS act on that.

------------------------------------------------

**Assuming you want to have python code trigger based on the front-end's interactions**

Not from python code as the props need to be JSON serialisable and the front-end wont have any understanding of how to signal the back-end.

You'll need to wire up a server that can either handle requests or a socket connection so that your front-end code can talk back to the python process. You'll also need to handle how the front-end signals the backend.
