### ISSUE TITLE
Some Clarifications

### ISSUE THREAD

**Issue by henhen87** [markfinger/python-react#89]
Hello,

I have been looking for some examples to serve React applications with isomorphic rendering using Python and I came upon this example. I am looking through the repo, and I can't quite grasp what the node server file you have does. Does it serve a purpose? It seems like it is not being using at all. The index.html file you are rendering seems like it is from the Python file, and correct me if I am wrong, but I didn't see and APIs to a NodeJS server file in here (the python server). Also, the NodeJS server file has a post request endpont '/render', but nowhere in your application does it make this request. 

Does your node js file serve a purpose and is there a better way to implent server side rendering with python, other than sending individual components one at a time and sending props. I feel like this having all the python routes to serve individual components defeats the purpose of Reacts Single Page Application principle.

**Comment by markfinger** [comment]
The `python-react` lib is the wiring to pass data from a python process to a node server that handles loading in the React components and then rendering them with the data provided. Once the rendering is complete, the markup generated is sent back to the python process. 

In the example apps, the interactions with the render server are abstracted behind calls to the library code. You can find the lib code in https://github.com/markfinger/python-react/tree/master/react

> Does your node js file serve a purpose and is there a better way to implent server side rendering with python

As above, the node server just handles loading + rendering. You can certainly load some JS into python wrappers around JS VMs. This approach can be tempting as it appears you wont need a seperate process, in practice though, you will eventually run into issues where the code relies on either Node or Browser globals. Working around those issues will probably cost more in time/effort than managing a node-based render pipeline.

> I feel like this having all the python routes to serve individual components defeats the purpose of Reacts Single Page Application principle.

I'm not entirely sure what you mean by "Reacts Single Page Application principle", React itself is a tool that can be used in a variety of different ways, one of which is as a part in an SPA. Using React does not require you to build an SPA. In fact, large parts of the industry are steadily moving away from SPA systems due to an understanding that they come with enormous overheads and few benefits. In most cases, I'd recommend using a conventional CMS system and integrating React for the cases where you need interactivity.
